# Dockerfile.node-red
FROM nodered/node-red:latest

# Instalar el nodo necesario para conectarse a InfluxDB
RUN npm install node-red-contrib-influxdb

# Copiar el flujo predefinido directamente desde su nueva ubicación
COPY services/node-red/flujo_reto.json /data/flows.json

# Copiar el script para insertar el token de InfluxDB
COPY services/node-red/set_token.sh /usr/src/node-red/set_token.sh
RUN chmod +x /usr/src/node-red/set_token.sh

# Ejecutar el script para reemplazar el token antes de iniciar Node-RED
ENTRYPOINT ["/bin/bash", "-c", "/usr/src/node-red/set_token.sh && npm start"]
