{
 "title": "Data-Real-Time-Node-red",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Velocidad-Viento-Tiempo-real", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Velocidad-Viento",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather-realtime\")\n  |> filter(fn: (r) => r[\"_field\"] == \"viento_velocidad\")\n  |> filter(fn: (r) => r[\"tag_ciudad\"] == \"Barcelona\" or r[\"tag_ciudad\"] == \"Bilbao\" or r[\"tag_ciudad\"] == \"Madrid\" or r[\"tag_ciudad\"] == \"Seville\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Velocidad-Viento",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather-realtime\")\n  |> filter(fn: (r) => r[\"_field\"] == \"viento_velocidad\")\n  |> filter(fn: (r) => r[\"tag_ciudad\"] == \"Barcelona\" or r[\"tag_ciudad\"] == \"Bilbao\" or r[\"tag_ciudad\"] == \"Madrid\" or r[\"tag_ciudad\"] == \"Seville\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Humedad-Tiempo-Real", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Humedad-Real-TIme",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather-realtime\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humedad\")\n  |> filter(fn: (r) => r[\"tag_ciudad\"] == \"Barcelona\" or r[\"tag_ciudad\"] == \"Bilbao\" or r[\"tag_ciudad\"] == \"Madrid\" or r[\"tag_ciudad\"] == \"Seville\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Humedad-Real-time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather-realtime\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humedad\")\n  |> filter(fn: (r) => r[\"tag_ciudad\"] == \"Barcelona\" or r[\"tag_ciudad\"] == \"Bilbao\" or r[\"tag_ciudad\"] == \"Madrid\" or r[\"tag_ciudad\"] == \"Seville\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Temperaturas-Tiempo-Real", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Temperaturas",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather-realtime\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura\")\n  |> filter(fn: (r) => r[\"tag_ciudad\"] == \"Seville\" or r[\"tag_ciudad\"] == \"Madrid\" or r[\"tag_ciudad\"] == \"Bilbao\" or r[\"tag_ciudad\"] == \"Barcelona\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperaturas-Real-time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather-realtime\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura\")\n  |> filter(fn: (r) => r[\"tag_ciudad\"] == \"Seville\" or r[\"tag_ciudad\"] == \"Madrid\" or r[\"tag_ciudad\"] == \"Bilbao\" or r[\"tag_ciudad\"] == \"Barcelona\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperaturas-Pie chart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather-realtime\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura\")\n  |> filter(fn: (r) => r[\"tag_ciudad\"] == \"Seville\" or r[\"tag_ciudad\"] == \"Madrid\" or r[\"tag_ciudad\"] == \"Bilbao\" or r[\"tag_ciudad\"] == \"Barcelona\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}